{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels: {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
{{- end }}
{{- end }}