apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: udp
      protocol: UDP
      port: {{ .Values.service.gamePort }}
      nodePort: {{ .Values.service.gamePort }}
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.gamePort }}
      nodePort: {{ .Values.service.gamePort }}
  selector:
    {{- include "satisfactory.selectorLabels" . | nindent 4 }}
