nameOverride: ""
fullnameOverride: ""

image:
  repository: wolveix/satisfactory-server
  pullPolicy: IfNotPresent
  tag: "v1.8.5"

config:
  maxPlayers: 8
  crashReport: true
  steamBeta: false
  skipUpdate: false
  autosaveCount: 3
  autosaveInterval: 900
  autoPause: true
  saveOnDisconnect: true
  seasonalEvents: true
  networkQuality: 0 # 0 (low) to 3 (ultra)

replicaCount: 1

serviceAccount:
  name: ""
  create: true
  automount: true
  annotations: {}

service:
  gamePort: 7777
  beaconPort: 15000
  queryPort: 15777

persistence:
  enabled: true
  size: 10Gi
  existingClaim: ""

podSecurityContext:
  allowPrivilegeEscalation: false

securityContext:
  fsGroup: 1000

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

resources: {}
nodeSelector: {}
affinity: {}
tolerations: []
